# Generated by Django 6.0.3 on 2026-04-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outing',
            options={},
        ),
        migrations.AddField(
            model_name='outing',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
