# Generated by Django 6.0.3 on 2026-05-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_alter_outing_options_outing_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outing',
            options={'ordering': ['-out_time']},
        ),
        migrations.RemoveField(
            model_name='outing',
            name='reason',
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ENTC', 'ENTC'), ('MECH', 'MECH')], default='CSE', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('BOYS', 'Boys'), ('GIRLS', 'Girls')], default='BOYS', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.CharField(choices=[('FY', 'FY'), ('SY', 'SY'), ('TY', 'TY'), ('BE', 'BE')], default='FY', max_length=5),
        ),
    ]
