# Generated by Django 6.0.3 on 2026-05-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_alter_outing_options_remove_outing_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ENTC', 'ENTC'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('ECE', 'ECE')], default='CSE', max_length=10),
        ),
    ]
