# Generated by Django 6.0.3 on 2026-05-17 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_alter_student_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='fee',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fee',
            name='pending_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fee',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Partial', 'Partial'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ENTC', 'ENTC'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('ECE', 'ECE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('BOYS', 'Boys'), ('GIRLS', 'Girls')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='hostel_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter valid 10 digit number', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='room_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(choices=[('FY', 'FY'), ('SY', 'SY'), ('TY', 'TY'), ('BE', 'BE')], max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter valid 10 digit number', regex='^\\d{10}$')]),
        ),
    ]
