# Generated by Django 6.0.3 on 2026-05-17 15:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_rename_amount_fee_total_amount_fee_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outing',
            options={},
        ),
        migrations.RemoveField(
            model_name='outing',
            name='date',
        ),
        migrations.AddField(
            model_name='outing',
            name='destination',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outing',
            name='in_latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outing',
            name='in_longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outing',
            name='out_latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outing',
            name='out_longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outing',
            name='reason',
            field=models.TextField(default='Old outing record'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outing',
            name='status',
            field=models.CharField(choices=[('OUT', 'OUT'), ('RETURNED', 'RETURNED')], default='OUT', max_length=20),
        ),
        migrations.AlterField(
            model_name='outing',
            name='out_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='outing',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.student'),
        ),
    ]
